# Computation on Arrays - Broadcasting

In [1]:
import numpy as np

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [4]:
# Adding a scalar to an array
a + 5

array([6, 7, 8])

In [11]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
M + a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [13]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [14]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Rules of Broadcasting

**Rule 1:** If the two arrays differ in their number of dimensions,
the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension,
the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
# Adding a 2D array to a 1D array
# Broadcasting example 1

M = np.ones((2, 3))
a = np.arange(3)

In [16]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
# Broadcasting example 2

a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [18]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])