In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
i = np.array([2, 1, 8, 4])
i

array([2, 1, 8, 4])

In [4]:
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [5]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 2., 2., 2., 0., 0., 0., 0., 0.])