In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.2'

Understanding data types in python:

    - In C data types must be explicitly declared, while in python not
    - Python is a dynamically typed language
    - Python variables are more than just a value, they contain more info **
        - a variable (eg: integer) in python is actually a C structure
        


A python list is more than just a list

In [4]:
L = list(range(10))
L


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

Fixed type arrays in python
Seen below: i is a type code indication the contents are integers

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np


In [8]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Unlike python lists, numpy arrays can explicitly be multi-dimensional       

In [11]:
#nested lists result in multi-dimensional arrays
np.array([range(i, i + 10) for i in [2, 4, 6]])

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

Creating arrays from scratch:

In [12]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.21098892, 0.75119649, 0.56393819],
       [0.60267693, 0.33652111, 0.27359855],
       [0.38959902, 0.86884339, 0.34338702]])

In [18]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.83616476, -0.7571867 , -1.44075735],
       [-1.12879826,  1.57438363,  0.02718181],
       [ 0.68798059,  0.76812201,  0.19294288]])

In [19]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 4, 2],
       [6, 5, 7],
       [8, 9, 2]], dtype=int32)

In [20]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

NumPy standard data types:
numpy is built in C language


In [22]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [23]:
print("Rohan")

Rohan


Basics of NumPy Arrays:

In [24]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


In [25]:
print("NumPy array properties")
print("x3 number of dimensions: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


NumPy array properties
x3 number of dimensions:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [26]:
print("dtype: ", x3.dtype)

dtype:  int32


In [27]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


Array concatenation and splitting
    

In [ ]:
# Concatenation of arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
np.concatenate([x, y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  4  5  6  7  8  9 10 99 99 99]


In [31]:
# Concatenation of two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [33]:
# Concatenate along the first axis
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [35]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# Vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [37]:
# Horizontally stack the arrays
y = np.array([[99],
              [99]])

np.hstack([grid, y])


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting of arrays

In [39]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [ 3 99 99] [3 2 1]
