In [1]:
import numpy as np

Manually sorting algorithm

In [3]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [4]:
x = np.array([2, 1, 4, 3, 5])
print(selection_sort(x))

[1 2 3 4 5]


Bogo sort: randomly shuffles an array until the array appears to be sorted. Pure chance!

In [5]:
def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
    return x

In [13]:
x = np.array([2, 1, 4, 3, 5])
print(bogosort(x))

[1 2 3 4 5]


Fast sorting in NumPy: Different methods
    merge sort
    heap sort
    quick sort
    


In [14]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [9]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [12]:
x.sort()
print(x)

[1 2 3 4 5]


In [15]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [17]:
x[i]

array([1, 2, 3, 4, 5])

In [18]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [19]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [20]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)