The slowness of loops


In [3]:
import numpy as np

In [4]:
np.random.seed(0)

def compute_reciprocal(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)



In [5]:
%timeit compute_reciprocal(values)

12.3 μs ± 223 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
big_array = np.random.randint(1, 100, size=1000000)

In [7]:
%timeit compute_reciprocal(big_array)


2.34 s ± 38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


UFunc's: vectorized operations/approach

In [8]:
print(compute_reciprocal(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [9]:
%timeit (1.0 / big_array)

2.67 ms ± 135 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [11]:
# Vectorized operations in Numpy are implemented via ufuncs,
# whose main purpose is to quickly execute repeated operations on values in Numpy arrays
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Specialized ufuncs

In [12]:
from scipy import special

In [13]:
# Gamma function (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [14]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


Advanced ufunc features:
- specifying output

In [15]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)


[ 0. 10. 20. 30. 40.]


In [16]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


Aggregates:

For example, we can reduce an array with a particular operation   by passing the reduce method of the ufunc

In [17]:
x = np.arange(1, 6)
np.add.reduce(x)

np.int64(15)

In [18]:
np.multiply.reduce(x)

np.int64(120)

In [19]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

Outer products:
Enables creation of multiplication table

In [20]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Another extremely useful feature of ufuncs is the ability to operate between arrays of different sizes and shapes, a set of operations known as broadcasting

Aggregations: Min, Max, and Everything in Between

Summing the values in an array

In [59]:
L = np.random.random(100)
sum(L)

np.float64(53.427293572552756)

In [61]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

89.1 ms ± 658 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
325 μs ± 28 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [65]:
min(big_array), max(big_array)

(np.float64(2.067514368597756e-07), np.float64(0.999997425247757))

In [66]:
np.min(big_array), np.max(big_array)

(np.float64(2.067514368597756e-07), np.float64(0.999997425247757))

In [67]:
%timeit min(big_array)
%timeit np.min(big_array)

65.4 ms ± 595 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
121 μs ± 2.25 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [68]:
print(big_array.min(), big_array.max(), big_array.sum())

2.067514368597756e-07 0.999997425247757 499881.7701440746


In [ ]:
# Multidimensional aggregates

In [69]:
M = np.random.random((3, 4))
print(M)

[[0.1650611  0.45580246 0.63329748 0.58415216]
 [0.52633925 0.4815272  0.64783536 0.27584598]
 [0.49042792 0.91814555 0.60334268 0.36310205]]


In [72]:
M.sum()

np.float64(6.144879203068416)

In [73]:
M.min(axis=0)

array([0.1650611 , 0.45580246, 0.60334268, 0.27584598])

In [74]:
M.max(axis=1)

array([0.63329748, 0.64783536, 0.91814555])